# Generated by Django 4.1.3 on 2022-12-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleTrail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('prefecture', models.CharField(max_length=9)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=13)),
                ('length', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('photo_url', models.CharField(max_length=2048)),
                ('map_url', models.CharField(max_length=2048)),
            ],
        ),
    ]
