# Generated by Django 4.1.3 on 2022-12-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('prefecture', models.CharField(max_length=9)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=13)),
                ('length', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('photo_url', models.CharField(max_length=2048, null=True)),
                ('map_url', models.CharField(max_length=2048, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SingleTrail',
        ),
    ]
