# Generated by Django 4.1.3 on 2022-12-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_trail_delete_singletrail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='trail',
            name='map_url',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='trail',
            name='photo_url',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
