# Generated by Django 4.1.3 on 2022-12-05 08:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='TrailLike',
        ),
    ]
