# Generated by Django 4.1.3 on 2022-12-06 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0008_rename_like_traillike'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailCompletion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completion', models.BooleanField()),
                ('date', models.DateField()),
                ('trail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
