# Generated by Django 4.1.3 on 2022-12-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_account_user_alter_trailcomment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
    ]
