# Generated by Django 4.1.3 on 2022-12-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_trailmessages'),
        ('backend', '0011_remove_account_email'),
    ]

    operations = [
    ]
