# Generated by Django 4.1.3 on 2022-12-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rename_badges_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailmessage',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='trailmessage',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
