# Generated by Django 4.1.3 on 2022-12-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rename_badges_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailCompletionLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('length', models.IntegerField()),
            ],
        ),
    ]
