# Generated by Django 4.1.3 on 2022-12-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_trailcompletionlength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailmessage',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='trailmessage',
            name='likes',
        ),
        migrations.AddField(
            model_name='trailmessage',
            name='likes',
            field=models.ManyToManyField(related_name='message_likes', to='backend.account'),
        ),
    ]
