# Generated by Django 4.1.3 on 2022-12-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_remove_trailmessage_likes_trailmessagelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailcomment',
            name='userName',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
