# Generated by Django 4.1.3 on 2022-12-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='from_email',
            field=models.CharField(max_length=254),
        ),
    ]
